on:
  push:
    branches:
      - main
jobs:
  web-export:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ— Setup repo
        uses: actions/checkout@v2
      - name: ğŸ— Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache-dependency-path: voracious/yarn.lock
          cache: yarn

      - name: ğŸ“¦ Install dependencies
        working-directory: ./voracious
        run: yarn install

      - name: ğŸ§± Build app
        working-directory: ./voracious
        run: expo export:web
